### PR TITLE
Update v2 Themes

### PR DESCRIPTION
**Pull request by Puyodead1**
Add the BetterDiscord Contributor Badge, Fix a typo in css.

https://i.imgur.com/tuQccfK.png

### CODE REVIEW

**Comment by satoru8** [comment]
If anyone wants to help with v2 Themes, then push to this PR for now.

**Comment by zedansk** [comment]
can go on a typo hunt

**Comment by Puyodead1** [comment]
https://github.com/Puyodead1-Development/BDv2/commit/9c4ae1a5c92b9dcfe68367ee456969a279f72ca4
Update Nova Theme

**Comment by satoru8** [comment]
Going to merge this and keep newUpdates branch open to work on.

**Pull request merged**
